"""
Step 9: Generate PD1 — Kidney Stone CIF Files (PXRD + FTIR)
=============================================================
Reads patient_stones.csv and generates one CIF file per stone episode
containing synthetic powder X-ray diffraction and FTIR spectroscopy data.

Each mineral has reference PXRD peaks and FTIR bands. Mixed stones are
generated by summing reference patterns weighted by composition percentage,
with Gaussian noise added.

Usage:
    python generators/generate_pd1.py \
        --stones ~/securecomputing-data/pd0/patient_stones.csv \
        --output-dir ~/securecomputing-data/pd1
"""

import argparse
import csv
import json
import numpy as np
from pathlib import Path


# Reference PXRD peaks (2-theta, relative intensity) for Cu K-alpha radiation
# Based on published powder diffraction data for each mineral
PXRD_REFERENCE = {
    'whewellite': [
        (14.93, 45), (15.78, 55), (20.05, 30), (23.42, 20),
        (24.37, 100), (25.12, 60), (28.34, 40), (29.42, 35),
        (30.12, 75), (32.01, 45), (33.45, 30), (36.12, 40),
        (37.89, 25), (38.56, 35), (40.12, 20), (42.34, 28),
        (44.56, 15), (46.78, 22), (48.12, 14), (50.34, 18),
    ],
    'weddellite': [
        (14.28, 100), (20.10, 35), (23.30, 25), (24.50, 40),
        (27.80, 30), (30.50, 20), (32.20, 55), (35.60, 25),
        (38.10, 20), (40.80, 15), (43.20, 18), (45.50, 12),
        (47.80, 10), (50.10, 8),
    ],
    'hydroxyapatite': [
        (25.87, 100), (28.12, 20), (28.96, 30), (31.77, 80),
        (32.19, 75), (32.90, 70), (34.05, 35), (39.81, 25),
        (46.71, 30), (49.47, 25), (50.49, 15), (51.28, 20),
    ],
    'uric_acid': [
        (12.30, 40), (16.50, 55), (18.90, 30), (21.40, 100),
        (22.80, 45), (25.10, 35), (27.60, 60), (28.90, 25),
        (31.20, 20), (33.80, 30), (36.40, 15), (39.10, 18),
        (42.50, 12), (45.80, 10),
    ],
    'struvite': [
        (15.80, 70), (20.80, 100), (21.50, 45), (26.90, 35),
        (30.50, 55), (33.20, 40), (34.80, 30), (36.50, 25),
        (38.90, 20), (41.20, 15), (44.60, 18), (47.30, 12),
    ],
    'cystine': [
        (13.20, 50), (17.80, 35), (19.50, 100), (22.10, 60),
        (24.80, 45), (28.30, 30), (30.90, 40), (33.50, 25),
        (36.80, 20), (39.40, 15), (42.10, 18), (45.60, 10),
    ],
    'brushite': [
        (11.68, 100), (20.93, 60), (23.39, 35), (29.26, 80),
        (30.51, 45), (34.11, 30), (37.10, 25), (41.50, 20),
        (45.20, 15), (48.80, 12),
    ],
}

# Reference FTIR bands (wavenumber cm-1, transmittance %)
# Lower transmittance = stronger absorption
FTIR_REFERENCE = {
    'whewellite': [
        (3600, 92), (3430, 42), (3340, 38), (3250, 45), (3100, 78),
        (2900, 89), (1620, 22), (1480, 65), (1320, 28), (1100, 72),
        (950, 82), (885, 75), (780, 35), (660, 52), (520, 42),
    ],
    'weddellite': [
        (3600, 90), (3480, 35), (3380, 40), (3200, 50), (2900, 88),
        (1640, 25), (1480, 60), (1330, 32), (1100, 70), (950, 80),
        (885, 72), (770, 55), (660, 50), (520, 45),
    ],
    'hydroxyapatite': [
        (3570, 40), (3450, 75), (1650, 80), (1460, 55), (1420, 58),
        (1090, 20), (1040, 15), (960, 30), (870, 65), (630, 45),
        (600, 40), (570, 35), (475, 50),
    ],
    'uric_acid': [
        (3600, 88), (3400, 70), (3120, 35), (2800, 80), (1700, 20),
        (1650, 25), (1590, 30), (1480, 45), (1400, 40), (1230, 50),
        (1120, 55), (1000, 60), (880, 65), (780, 50), (620, 55),
        (500, 60),
    ],
    'struvite': [
        (3600, 85), (3400, 50), (3200, 55), (2900, 75), (2400, 70),
        (1680, 60), (1600, 55), (1440, 50), (1010, 20), (890, 65),
        (760, 55), (570, 40), (470, 50),
    ],
    'cystine': [
        (3600, 88), (3400, 60), (3200, 55), (2900, 50), (2550, 40),
        (1600, 45), (1520, 50), (1400, 55), (1300, 50), (1200, 55),
        (1060, 60), (940, 55), (860, 60), (700, 50), (540, 55),
    ],
    'brushite': [
        (3550, 40), (3480, 35), (3280, 45), (3170, 50), (2900, 80),
        (2400, 70), (1650, 55), (1220, 60), (1135, 50), (1060, 25),
        (1000, 30), (870, 55), (790, 60), (660, 50), (580, 45),
        (530, 40),
    ],
}

# Standard 2-theta range for PXRD
TWOTHETA_RANGE = np.arange(10.0, 55.0, 0.5)
# Standard wavenumber range for FTIR
WAVENUMBER_RANGE = np.arange(400, 4001, 50)[::-1]  # High to low (convention)


def generate_pxrd_pattern(composition, noise_level=0.05):
    """Generate a PXRD pattern from mineral composition."""
    pattern = np.zeros_like(TWOTHETA_RANGE, dtype=float)

    for mineral, fraction in composition.items():
        if mineral not in PXRD_REFERENCE:
            continue
        peaks = PXRD_REFERENCE[mineral]
        for peak_pos, peak_intensity in peaks:
            # Gaussian peak shape
            sigma = 0.15 + np.random.uniform(-0.03, 0.03)  # Peak width variation
            peak = peak_intensity * fraction * np.exp(-0.5 * ((TWOTHETA_RANGE - peak_pos) / sigma) ** 2)
            pattern += peak

    # Add noise
    noise = np.random.normal(0, noise_level * pattern.max(), len(pattern))
    pattern = np.maximum(pattern + noise, 0)

    return pattern


def generate_ftir_spectrum(composition, noise_level=0.03):
    """Generate an FTIR transmittance spectrum from mineral composition."""
    # Start with 100% transmittance (no absorption)
    spectrum = np.ones_like(WAVENUMBER_RANGE, dtype=float) * 95.0

    for mineral, fraction in composition.items():
        if mineral not in FTIR_REFERENCE:
            continue
        bands = FTIR_REFERENCE[mineral]
        for band_pos, band_transmittance in bands:
            # Absorption dip (Lorentzian-ish shape)
            width = 30 + np.random.uniform(-5, 5)
            absorption_depth = (95.0 - band_transmittance) * fraction
            dip = absorption_depth / (1 + ((WAVENUMBER_RANGE - band_pos) / width) ** 2)
            spectrum -= dip

    # Add noise and clamp
    noise = np.random.normal(0, noise_level * 10, len(spectrum))
    spectrum = np.clip(spectrum + noise, 5, 98)

    return spectrum


def write_cif(filepath, mrn, episode_num, episode_date, stone_type, composition,
              pxrd_2theta, pxrd_intensity, ftir_wavenumber, ftir_transmittance):
    """Write a CIF file with PXRD and FTIR data."""
    # Determine primary mineral
    primary_mineral = max(composition, key=composition.get)
    primary_pct = composition[primary_mineral] * 100

    with open(filepath, 'w') as f:
        f.write("#" + "=" * 77 + "\n")
        f.write(f"# Synthetic Kidney Stone Analysis - Powder X-ray Diffraction + FTIR\n")
        f.write(f"# Patient MRN: {mrn}\n")
        f.write(f"# Episode: {episode_num}\n")
        f.write(f"# Analysis date: {episode_date}\n")
        f.write(f"# Stone type: {stone_type}\n")
        f.write(f"# Composition: {json.dumps({k: round(v*100, 1) for k, v in composition.items()})} %\n")
        f.write(f"#\n")
        f.write(f"# THIS IS SYNTHETIC DATA - NOT FROM A REAL PATIENT\n")
        f.write("#" + "=" * 77 + "\n\n")

        f.write(f"data_stone_{mrn}_{episode_num:03d}\n\n")
        f.write(f"_audit_creation_date             {episode_date}\n")
        f.write(f"_audit_creation_method           'securecomputing-datagen'\n\n")
        f.write(f"_chemical_name_common            'Kidney stone specimen'\n")
        f.write(f"_chemical_compound_source        'Patient {mrn}'\n\n")
        f.write(f"_pd_phase_name                   '{primary_mineral}'\n")
        f.write(f"_pd_phase_mass_%                 {primary_pct:.1f}\n\n")

        # PXRD data
        f.write("# Powder XRD data (Cu K-alpha, lambda=1.5406 Ang)\n\n")
        f.write("loop_\n")
        f.write("_pd_meas_2theta_scan\n")
        f.write("_pd_meas_intensity_total\n")
        for tt, intensity in zip(pxrd_2theta, pxrd_intensity):
            if intensity > 0.5:  # Only write non-trivial points
                f.write(f"{tt:.2f}   {intensity:.1f}\n")

        f.write("\n# FTIR data (wavenumber cm-1, transmittance %)\n\n")
        f.write("loop_\n")
        f.write("_pd_ir_wavenumber\n")
        f.write("_pd_ir_transmittance\n")
        for wn, trans in zip(ftir_wavenumber, ftir_transmittance):
            f.write(f"{wn:.0f}  {trans:.1f}\n")


def main():
    parser = argparse.ArgumentParser(description='Generate PD1 kidney stone CIF files')
    parser.add_argument('--stones', required=True, help='Path to patient_stones.csv')
    parser.add_argument('--output-dir', required=True, help='Output directory for CIF files')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    args = parser.parse_args()

    np.random.seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files_written = 0
    with open(args.stones, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['stone_type'] == 'none':
                continue

            mrn = row['mrn']
            episode_num = int(row['episode_number'])
            episode_date = row['episode_date']
            stone_type = row['stone_type']
            composition = json.loads(row['composition'])

            # Generate patterns
            pxrd_pattern = generate_pxrd_pattern(composition)
            ftir_spectrum = generate_ftir_spectrum(composition)

            # Write CIF
            filename = f"stone_{mrn}_{episode_num:03d}.cif"
            filepath = output_dir / filename
            write_cif(
                filepath, mrn, episode_num, episode_date, stone_type, composition,
                TWOTHETA_RANGE, pxrd_pattern, WAVENUMBER_RANGE, ftir_spectrum
            )
            files_written += 1

            if files_written % 1000 == 0:
                print(f"  {files_written} files written...")

    print(f"\nPD1 generation complete: {files_written} CIF files → {output_dir}")


if __name__ == '__main__':
    main()
